---

- hosts: all
  become: true
  tasks:

  - name: Updated respository index
    apt:
      update_cache: yes

  - name: Install apache2 package
    apt:
      name: apache2
      state: absent

  - name: Add package for php apache
    apt:
      name: libapache2-mod-php
      state: absent
